import { User } from '../class/user';

export const USERS: User[] = [
    {
        'loyaltyId': '1659010564799',
        'userName': 'pharetra',
        'firstName': 'firstNehru',
        'lastName': 'lastWesley',
        'phoneNumber': '5091987310',
        'email': 'non@vestibulumnequesed.ca',
        'zipCode': '05155',
        'address1': 'Ap #929-6409 Dui. Road',
        'address2': 'Ap #327-1839 Dapibus Road',
        'city': 'Paredones',
        'state': 'Aenean egestas',
        'emailOption': false,
        'subscribeEmail': false,
        'subscribePhone': true,
        'password': ''
    },
    {
        'loyaltyId': '1645122175199',
        'userName': 'eleifend',
        'firstName': 'firstKuame',
        'lastName': 'lastAmaya',
        'phoneNumber': '6332786512',
        'email': 'egestas.ligula.Nullam@ac.ca',
        'zipCode': '410759',
        'address1': 'Ap #159-5000 Luctus St.',
        'address2': '8691 Vestibulum Rd.',
        'city': 'Melton',
        'state': 'Mauris vestibulum,',
        'emailOption': true,
        'subscribeEmail': false,
        'subscribePhone': true,
        'password': ''
    },
    {
        'loyaltyId': '1623052911299',
        'userName': 'ipsum',
        'firstName': 'firstHanae',
        'lastName': 'lastGrace',
        'phoneNumber': '4180439241',
        'email': 'eu@Nam.net',
        'zipCode': '97778',
        'address1': '2279 At St.',
        'address2': '744-6600 Tortor. Avenue',
        'city': 'Middlesbrough',
        'state': 'interdum. Nunc',
        'emailOption': true,
        'subscribeEmail': true,
        'subscribePhone': true,
        'password': ''
    },
    {
        'loyaltyId': '1648012996499',
        'userName': 'eu',
        'firstName': 'firstAyanna',
        'lastName': 'lastKennedy',
        'phoneNumber': '2067154475',
        'email': 'eu.odio@atpedeCras.org',
        'zipCode': '40305',
        'address1': 'Ap #672-6243 Eu, Rd.',
        'address2': 'P.O. Box 399, 3399 Nullam Avenue',
        'city': 'Brandon',
        'state': 'luctus felis',
        'emailOption': false,
        'subscribeEmail': false,
        'subscribePhone': true,
        'password': ''
    },
    {
        'loyaltyId': '1657012656499',
        'userName': 'dui.',
        'firstName': 'firstCynthia',
        'lastName': 'lastDante',
        'phoneNumber': '5748502512',
        'email': 'sed.libero.Proin@liberoProinmi.com',
        'zipCode': '66830',
        'address1': 'P.O. Box 275, 1403 Lorem Street',
        'address2': '4909 Lorem Street',
        'city': 'Fatehpur',
        'state': 'metus vitae',
        'emailOption': true,
        'subscribeEmail': true,
        'subscribePhone': false,
        'password': ''
    },
    {
        'loyaltyId': '1633070369399',
        'userName': 'enim',
        'firstName': 'firstNathaniel',
        'lastName': 'lastKatell',
        'phoneNumber': '6491944798',
        'email': 'molestie.dapibus.ligula@massa.ca',
        'zipCode': '27-828',
        'address1': 'Ap #626-8175 Tempor Av.',
        'address2': 'P.O. Box 297, 9648 Suspendisse Rd.',
        'city': 'San Luca',
        'state': 'vitae diam.',
        'emailOption': false,
        'subscribeEmail': false,
        'subscribePhone': false,
        'password': ''
    },
    {
        'loyaltyId': '1602072349799',
        'userName': 'iaculis,',
        'firstName': 'firstBuffy',
        'lastName': 'lastDawn',
        'phoneNumber': '2409877353',
        'email': 'Vivamus@nectempusmauris.co.uk',
        'zipCode': '1526',
        'address1': '3979 Magna. Street',
        'address2': 'P.O. Box 903, 8733 Feugiat. Street',
        'city': 'Colmar',
        'state': 'nisi. Cum',
        'emailOption': true,
        'subscribeEmail': false,
        'subscribePhone': false,
        'password': ''
    },
    {
        'loyaltyId': '1696122107099',
        'userName': 'erat',
        'firstName': 'firstUlla',
        'lastName': 'lastJerry',
        'phoneNumber': '5755289753',
        'email': 'at@Donecfringilla.edu',
        'zipCode': '292649',
        'address1': 'P.O. Box 569, 3641 Nulla St.',
        'address2': '4606 Et, Rd.',
        'city': 'Brye',
        'state': 'mi enim,',
        'emailOption': true,
        'subscribeEmail': true,
        'subscribePhone': true,
        'password': ''
    },
    {
        'loyaltyId': '1611060240099',
        'userName': 'nisi',
        'firstName': 'firstLeila',
        'lastName': 'lastGemma',
        'phoneNumber': '9382362017',
        'email': 'pretium.aliquet.metus@rutrumjustoPraesent.ca',
        'zipCode': 'M2Q 5CK',
        'address1': '205-873 Diam St.',
        'address2': 'P.O. Box 897, 9957 Tellus, Street',
        'city': 'Braives',
        'state': 'Maecenas malesuada',
        'emailOption': true,
        'subscribeEmail': true,
        'subscribePhone': true,
        'password': ''
    },
];
